# Release v4.4.4.0
### CLI
- no changes

### CSScriptLib
- Added `CSScript.EvaluatorConfig.CompilerOptions` for defining global compiler options for CodeDomEvaluator (RoslynEvaluator does not support string compiler options)
- Issue #291: CSScriptLib.CompilerException: error CS2021: File name '' is empty